### PR TITLE
Allow a team to be omitted from the rankings

### LINKED ISSUE #31: Opt-out of team rankings

### PR DESCRIPTION
**Pull request by nickfrostatx**
This closes #31.

This only contains the database and API portion of this change. This change does NOT include a UI change to allow users to toggle this setting on their own.

### CODE REVIEW

**Comment by nickago** [comment]
So I would recommend that this PR come with a UI implementation in addition to the API implementation. That way we can roll the feature to all platforms at once

**Comment by atti1a** [comment]
@jakahn What's the status on this PR? Are you using the code in it, or can I close this and move it to an issue?

**Comment by DeltaHeavy** [comment]
@atti1a Go ahead and either merge and create a UI issue or close it and open a full-stack issue, whichever you think is best. Thanks!

**Comment by atti1a** [comment]
Closing this issue due to stale code and lack of response

**Pull request closed without merging**
